---
- name: "Firewall: Allow HTTP from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: "Firewall: Allow HTTPS from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: "Firewall: Allow BGP from IPv4 peer"
  become: true
  community.general.ufw:
    rule: allow
    port: "179"
    proto: tcp
    from_ip: "{{ snappy_bgp_neighbor_v4 }}"

- name: "Firewall: Allow BGP from IPv6 peer"
  become: true
  community.general.ufw:
    rule: allow
    port: "179"
    proto: tcp
    from_ip: "{{ snappy_bgp_neighbor_v6 }}"

- name: "Firewall: Allow iperf3 TCP from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ iperf3_port }}"
    proto: tcp

- name: "Firewall: Allow iperf3 UDP from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ iperf3_port }}"
    proto: udp

- name: "Firewall: Allow xfr TCP from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ xfr_port }}"
    proto: tcp

- name: "Firewall: Allow xfr UDP from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ xfr_port }}"
    proto: udp

- name: "Firewall: Allow btest-rs TCP from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ btest_rs_port }}"
    proto: tcp

- name: "Firewall: Allow btest-rs UDP range from anywhere"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ btest_rs_port }}:{{ btest_rs_port | int + btest_rs_max_sessions | int + 256 }}"
    proto: udp
