---
- name: "Snappy: Network Tuning"
  ansible.builtin.import_tasks: network_tuning.yml
  tags:
    - network
    - tuning
    - performance

- name: "Snappy: Install BIRD"
  ansible.builtin.import_tasks: bird.yml
  tags:
    - bird
    - bgp

- name: "Snappy: iperf3"
  ansible.builtin.import_role:
    name: iperf3
  tags:
    - speedtest
    - iperf3

- name: "Snappy: xfr"
  ansible.builtin.import_role:
    name: xfr
  tags:
    - speedtest
    - xfr

- name: "Snappy: LibreSpeed"
  ansible.builtin.import_role:
    name: librespeed
  tags:
    - speedtest
    - librespeed

- name: "Snappy: TAUC Speed Test"
  ansible.builtin.import_role:
    name: tauc_speedtest
  tags:
    - speedtest
    - tauc

- name: "Snappy: OpenSpeedTest"
  ansible.builtin.import_role:
    name: openspeedtest
  tags:
    - speedtest
    - openspeedtest

- name: "Snappy: Nginx + TLS"
  ansible.builtin.import_tasks: nginx.yml
  tags:
    - nginx

- name: "Snappy: Firewall"
  ansible.builtin.import_tasks: firewall.yml
  tags:
    - firewall
