---
- name: "Snappy: Network Tuning"
  ansible.builtin.import_tasks: network_tuning.yml
  tags:
    - network
    - tuning
    - performance

- name: "Snappy: Install BIRD"
  ansible.builtin.import_tasks: bird.yml
  tags:
    - bird
    - bgp

- name: "Snappy: Speedtest"
  ansible.builtin.import_tasks: speedtest.yml
  tags:
    - speedtest

- name: "Snappy: Nginx + TLS"
  ansible.builtin.import_tasks: nginx.yml
  tags:
    - nginx

- name: "Snappy: iperf3"
  ansible.builtin.import_tasks: iperf3.yml
  tags:
    - iperf3

- name: "Snappy: Firewall"
  ansible.builtin.import_tasks: firewall.yml
  tags:
    - firewall
