---
- name: Restart libreixp_portal
  become: true
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: libreixp_portal.service

- name: Build virtualenv for ixp_web
  notify: Restart libreixp_portal
  become: true
  ansible.builtin.command:
    cmd: pipenv --python=/usr/bin/python3 sync
    chdir: /opt/sfmix/libreixp/ixp_web
  environment:
    PIPENV_VENV_IN_PROJECT: "true"
  register: libreixp_portal_pipenv_sync
  changed_when: "'All dependencies are now up-to-date!' in libreixp_portal_pipenv_sync.stdout"
