---
- name: Re-build alice-lg
  become: true
  community.docker.docker_image:
    build:
      path: /opt/alice/alice-lg
      network: host
    name: alice-lg
    tag: "{{ alice_git_repo_version | replace('/', '_') }}"
    source: build
    force_source: true
  notify: Remove alice container

- name: Remove alice container
  become: true
  community.docker.docker_container:
    name: alice
    state: absent

- name: Restart alice
  become: true
  community.docker.docker_container:
    name: alice
    restart: true
    state: started
