---
- name: "Teleport: remove_old_logs: Create systemd service file"
  become: true
  ansible.builtin.template:
    src: teleport_remove_old_logs.service.j2
    dest: /etc/systemd/system/teleport_remove_old_logs.service
    owner: root
    group: root
    mode: ug=rw,o=r

- name: "Teleport: remove_old_logs: Create systemd timer file"
  become: true
  ansible.builtin.template:
    src: teleport_remove_old_logs.timer.j2
    dest: /etc/systemd/system/teleport_remove_old_logs.timer
    owner: root
    group: root
    mode: ug=rw,o=r

- name: "Teleport: remove_old_logs: Enable and start systemd timer"
  become: true
  ansible.builtin.systemd:
    name: teleport_remove_old_logs.timer
    enabled: true
    state: started
