---
- name: Build a list of all peering_switch loopbacks
  ansible.builtin.set_fact:
    all_peering_switch_loopbacks: >
      {{ groups['peering_switch'] |
        map('extract', hostvars, 'interfaces') |
        map('selectattr', 'name', 'equalto', 'Loopback0') |
        sum(start=[]) |
        map(attribute='ip_addresses') |
        sum(start=[]) |
        map(attribute='address') |
        ansible.utils.ipaddr('address')
        }}
    local_loopbacks: >
      {{
        interfaces |
        selectattr('name', 'equalto', 'Loopback0') |
        map(attribute='ip_addresses') |
        sum(start=[]) |
        map(attribute='address') |
        ansible.utils.ipaddr('address')
      }}
- name: Build a list of all other peering_switch loopbacks
  ansible.builtin.set_fact:
    other_peering_switch_loopbacks: >
      {{
        all_peering_switch_loopbacks | difference(local_loopbacks) | sort
      }}

- name: "Template: General"
  when: (ansible_run_tags == ['all'] and ansible_skip_tags == []) or ('general' in ansible_run_tags) or ('general' not in ansible_skip_tags and ('general' in ansible_run_tags or ansible_run_tags == ['all']))
  delegate_to: localhost
  ansible.builtin.template:
    src: eos/general.j2
    dest: "{{ config_parts_dir }}/general.eos_config.txt"
    mode: ug=rw,o=r

- name: "Template: Interfaces"
  delegate_to: localhost
  when: (ansible_run_tags == ['all'] and ansible_skip_tags == []) or (interface_name in ansible_run_tags) or (interface_name not in ansible_skip_tags and (interface_name in ansible_run_tags or ansible_run_tags == ['all']))
  ansible.builtin.template:
    src: eos/interface.j2
    dest: "{{ config_parts_dir }}/interface_{{ interface_name | replace('/', '_') }}.eos_config.txt"
    mode: ug=rw,o=r
  tags:
    - interfaces
  with_items: "{{ interfaces | map(attribute='name') | sort }}"
  loop_control:
    loop_var: interface_name

- name: "Template OSPF"
  when: (ansible_run_tags == ['all'] and ansible_skip_tags == []) or ('ospf' in ansible_run_tags) or ('ospf' not in ansible_skip_tags and ('ospf' in ansible_run_tags or ansible_run_tags == ['all']))
  delegate_to: localhost
  ansible.builtin.template:
    src: eos/ospf.j2
    dest: "{{ config_parts_dir }}/ospf.eos_config.txt"
    mode: ug=rw,o=r

- name: "Template VLANs"
  when: (ansible_run_tags == ['all'] and ansible_skip_tags == []) or ('vlans' in ansible_run_tags) or ('vlans' not in ansible_skip_tags and ('vlans' in ansible_run_tags or ansible_run_tags == ['all']))
  delegate_to: localhost
  ansible.builtin.template:
    src: eos/vlans.j2
    dest: "{{ config_parts_dir }}/vlans.eos_config.txt"
    mode: ug=rw,o=r
