---
- name: "Push: General"
  arista.eos.eos_config:
    src: "{{ config_parts_dir }}/general.eos_config.txt"

- name: "Push: Interfaces"
  arista.eos.eos_config:
    before: "default interface {{ interface_name }}"
    # What's going on here!?
    # This reads the locally-built config file for each interface
    # (in `item`), splits it into newlines, and removes any empty lines
    lines: >
      {{ lookup(
        'file',
        (config_parts_dir ~ '/interface_' ~ interface_name | replace('/', '_') ~ '.eos_config.txt')) |
      split('\n') |
      select('string') |
      list }}
    replace: block
  tags:
    - interfaces
  with_items: "{{ interfaces | map(attribute='name') | sort }}"
  loop_control:
    loop_var: interface_name

- name: "Push: router ospf 1"
  arista.eos.eos_config:
    lines: >
      {{
        lookup('file', (config_parts_dir ~ "/ospf.eos_config.txt")) |
        split('\n') |
        select('string') |
        list
      }}
    parents:
      - router ospf 1
    before: "default router ospf 1"
    replace: block
