---
- name: Reload bgpd
  become: true
  ansible.builtin.service:
    name: bgpd
    state: reloaded

- name: Restart httpd
  become: true
  ansible.builtin.service:
    name: httpd
    state: reloaded
