---
# Install jq
- name: "Install jq (Linux)"
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.apt:
    name: jq

- name: "Install jq (OpenBSD)"
  when: ansible_system == "OpenBSD"
  become: true
  community.general.openbsd_pkg:
    name: jq

# participants.json
- name: "Template participants.yaml to a string"
  ansible.builtin.set_fact:
    participants_json_string: |
      {{
        lookup('template', 'participants.yaml.j2') |
        ansible.builtin.from_yaml |
        ansible.builtin.to_json(indent=4, sort_keys=True)
      }}

- name: Locally template participants.yaml for debugging
  delegate_to: localhost
  ansible.builtin.template:
    src: participants.yaml.j2
    dest: /tmp/participants.yaml

- name: Locally template participants.json for debugging
  delegate_to: localhost
  ansible.builtin.copy:
    dest: /tmp/participants.json
    content: "{{ participants_json_string }}"

- name: Validate participants.json
  ansible.utils.validate:
    data: "{{ participants_json_string }}"
    criteria: "{{ lookup('ansible.builtin.file', 'ixp-member-list.schema.json') }}"
    engine: ansible.utils.jsonschema

- name: Ensure participants.json output directory exists
  become: true
  ansible.builtin.file:
    path: "{{ participants_json_output_directory }}"
    state: directory
    owner: sfmix
    group: sfmix
    mode: ug=rwx,o=rx

- name: "Template participants.min.json"
  become: true
  ansible.builtin.copy:
    dest: "{{ participants_json_output_directory }}/participants.min.json"
    content: "{{ participants_json_string }}"
    owner: sfmix
    group: sfmix
    mode: ug=rw,o=r

- name: "Prettyify participants.min.json into participants.json"
  become: true
  ansible.builtin.shell:
    cmd: >
      jq --sort-keys .
      {{ participants_json_output_directory }}/participants.min.json
      > {{ participants_json_output_directory }}/participants.json
  changed_when: true

# participants_yaml.json
- name: "Template participants_table.yaml to a string"
  ansible.builtin.set_fact:
    participants_table_json_string: |
      {{
        lookup('template', 'participants_table.yaml.j2') |
        ansible.builtin.from_yaml |
        ansible.builtin.to_json(indent=4, sort_keys=True)
      }}

- name: "Template participants_table.min.json"
  become: true
  ansible.builtin.copy:
    dest: "{{ participants_json_output_directory }}/participants_table.min.json"
    content: "{{ participants_table_json_string }}"
    owner: sfmix
    group: sfmix
    mode: ug=rw,o=r

- name: "Prettyify participants_table.min.json into participants_table.json"
  become: true
  ansible.builtin.shell:
    cmd: >
      jq --sort-keys .
      {{ participants_json_output_directory }}/participants_table.min.json
      > {{ participants_json_output_directory }}/participants_table.json
  changed_when: true
