---
- name: "Firewall: Allow HTTP(S)"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - http
    - https

- name: "Dynamic DNS: Install RFC2136 Credentials file"
  become: true
  template:
    src: certbot_rfc2136.ini
    dest: /etc/certbot_rfc2136.ini
    owner: root
    group: root
    mode: u=rw,go=

- name: Install certbot
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python3-certbot-dns-rfc2136

- name: Start certbot with special parameters for wildcard
  become: true
  command:
    argv:
      - certbot
      - certonly
      - --dns-rfc2136
      - --agree-tos
      - --noninteractive
      - --email
      - tech-c@sfmix.org
      - -d
      - 'teleport.sfmix.org,*.teleport.sfmix.org'
      - --dns-rfc2136-credentials
      - /etc/certbot_rfc2136.ini
    creates: /etc/letsencrypt/renewal/teleport.sfmix.org.conf

- name: Generate dhparams file
  become: true
  openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048

- name: "Install certbot for teleport certs"
  become: true
  block:
    - include_role:
        name: certbot
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_deploy_hook: "service teleport restart"
        certbot_certs:
          - domains:
              - "teleport.sfmix.org"
              - "*.teleport.sfmix.org"
