---
- name: Install BIRD
  become: true
  ansible.builtin.apt:
    name: bird2

- name: Place generated BIRD config
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('env', 'HOME') }}/arouteserver/{{ inventory_hostname }}-bird.cfg"
    dest: /etc/bird/bird.conf
    mode: ug=rw,o=r
  notify: Reload bird

- name: Enable/start BIRD
  become: true
  ansible.builtin.service:
    name: bird
    enabled: true
    state: started
