---
- name: "Obscreen: Create directory: {{ obscreen.directory }}"
  become: true
  ansible.builtin.file:
    path: "{{ obscreen.directory }}"
    state: directory
    owner: "{{ obscreen.user }}"
    group: "{{ obscreen.group }}"
    mode: 0755

- name: "Obscreen: Pull docker-compose.yml file from https"
  become: true
  ansible.builtin.get_url:
    url: "{{ obscreen.docker_compose_url }}"
    dest: "{{ obscreen.directory }}/docker-compose.yml"
    owner: "{{ obscreen.user }}"
    group: "{{ obscreen.group }}"
    mode: 0644

- name: "Obscreen: Start docker-compose"
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ obscreen.directory }}"
    state: present
    pull: always # always pull the latest
    recreate: always
    remove_orphans: true

- name: "Create a dhparams file"
  become: true
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048

- name: "Firewall: Allow HTTP(S)"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - http
    - https

- name: "Install HTTPS/Nginx Reverse Proxy"
  become: true
  block:
    - name: "Install certbox and nginx"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - geerlingguy.certbot
        - geerlingguy.nginx
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: ["nginx.service"]
        certbot_certs:
          - domains:
              - "{{ obscreen.domain }}"
        nginx_remove_default_vhost: true
        nginx_server_tokens: "off"
        nginx_extra_http_options: |
          limit_req_zone $binary_remote_addr zone=ip:10m rate=5r/s;
        nginx_vhosts:
          - listen: "80"
            server_name: "_"
            return: "301 https://$host$request_uri"
          - listen: "443 ssl http2"
            server_name: "{{ obscreen.domain }}"
            extra_parameters: |
              ssl_certificate /etc/letsencrypt/live/{{ obscreen.domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ obscreen.domain }}/privkey.pem;
              ssl_dhparam /etc/ssl/certs/dhparam.pem;
              location / {
                limit_req zone=ip burst=12 delay=8;
                proxy_pass http://127.0.0.1:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
              }
