---
- name: "LibreIXP Portal: Install LibreIXP"
  ansible.builtin.import_tasks:
    file: libreixp_portal.yml
  tags:
    - portal_libreixp_portal

- name: "LibreIXP Portal: Install nginx"
  ansible.builtin.import_tasks:
    file: nginx.yml
  tags:
    - portal_nginx
