---
- name: "Create a dhparams file"
  become: true
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048


# - name: "Firewall: Allow HTTP(S)"
#   become: true
#   community.general.ufw:
#     rule: allow
#     port: "{{ item }}"
#   loop:
#     - http
#     - https

- name: Install systemd-cron for certbot
  become: true
  apt:
    pkg: systemd-cron
    state: present

- name: "Install HTTPS/Nginx Reverse Proxy"
  become: true
  block:
    - include_role:
        name: "{{ item }}"
      loop:
        - geerlingguy.certbot
        - geerlingguy.nginx
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_create_if_missing: true
        # certbot_create_standalone_stop_services: ["netbox.socket", "netbox.service"]
        certbot_certs:
          - domains:
              - "{{ portal_domain }}"
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "80"
            server_name: "_"
            return: "301 https://$host$request_uri"
          - listen: "8000"
            server_name: portal.teleport.sfmix.org
            extra_parameters: |
              location = /favicon.ico { access_log off; log_not_found off; }
              location /static/ {
                alias /opt/sfmix/ixp_web/staticfiles/;
              }
              location / {
                include proxy_params;
                proxy_pass http://unix:/run/libreixp_portal.sock;
              }
          - listen: "443 ssl http2"
            server_name: "{{ portal_domain }}"
            extra_parameters: |
              ssl_certificate /etc/letsencrypt/live/{{ portal_domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ portal_domain }}/privkey.pem;
              ssl_dhparam /etc/ssl/certs/dhparam.pem;
              location = /favicon.ico { access_log off; log_not_found off; }
              location /static/ {
                alias /opt/sfmix/ixp_web/staticfiles/;
              }
              location / {
                include proxy_params;
                proxy_pass http://unix:/run/libreixp_portal.sock;
              }
