---
- name: "Create a dhparams file"
  become: true
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048


# - name: "Firewall: Allow HTTP(S)"
#   become: true
#   community.general.ufw:
#     rule: allow
#     port: "{{ item }}"
#   loop:
#     - http
#     - https

- name: Install systemd-cron for certbot
  become: true
  ansible.builtin.apt:
    pkg: systemd-cron
    state: present

- name: "Create certbot hooks directories"
  ansible.builtin.file:
    path: /etc/letsencrypt/renewal-hooks/{{ item }}
    state: directory
    mode: u=rwx,go=rx
    owner: root
    group: root
  with_items:
    - pre
    - post

- name: "Template ufw pre-script (disable Firewall)"
  become: true
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/pre/ufw_stop.sh
    content: "#!/bin/bash\nufw disable\n"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=

- name: "Template ufw post-script (disable Firewall)"
  become: true
  ansible.builtin.copy:
    dest: /etc/letsencrypt/renewal-hooks/post/ufw_stop.sh
    content: "#!/bin/bash\nufw enable\n"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=

- name: "Install HTTPS/Nginx Reverse Proxy"
  become: true
  block:
    - name: "Install HTTPS/Nginx Reverse Proxy"
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - geerlingguy.certbot
        - geerlingguy.nginx
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_deploy_hook: "service nginx restart"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: ["nginx.service"]
        certbot_certs:
          - domains:
              - "{{ portal_domain }}"
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "80"
            server_name: "_"
            return: "301 https://$host$request_uri"
          - listen: "8000"
            server_name: portal.teleport.sfmix.org
            extra_parameters: |
              location = /favicon.ico { access_log off; log_not_found off; }
              location /static/ {
                alias /opt/sfmix/libreixp/ixp_web/staticfiles/;
              }
              location / {
                include proxy_params;
                proxy_pass http://unix:/run/libreixp_portal.sock;
                proxy_read_timeout 120;
              }
          - listen: "443 ssl http2"
            server_name: "{{ portal_domain }}"
            extra_parameters: |
              ssl_certificate /etc/letsencrypt/live/{{ portal_domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ portal_domain }}/privkey.pem;
              ssl_dhparam /etc/ssl/certs/dhparam.pem;
              location = /favicon.ico { access_log off; log_not_found off; }
              location /static/ {
                alias /opt/sfmix/libreixp/ixp_web/staticfiles/;
              }
              location / {
                include proxy_params;
                proxy_pass http://unix:/run/libreixp_portal.sock;
                proxy_read_timeout 120;
              }
