---
- connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - ansible.builtin.import_tasks:
        file: roles/sfmix_server/tasks/download_ssh_keys_from_github.yml

- hosts: servers
  roles:
    - sfmix_server

- hosts: netbox
  become: true
  tags:
    - netbox
  roles:
    - ixp_netbox

- hosts: netbox
  become: true
  tags:
    - netbox
  roles:
    - geerlingguy.postgresql
    - DavidWittman.redis
    - lae.netbox

- hosts: metrics
  tags:
    - metrics
  roles:
    - docker_engine
    - sflow_rt
    - prometheus
    - grafana

- hosts: teleport
  tags:
    - teleport
  roles:
    - teleport

- hosts: portal
  become: true
  tags:
    - portal
    - redis
    - postgres
  roles:
    - geerlingguy.postgresql
    - DavidWittman.redis

- hosts: portal
  tags:
    - portal
  collections:
    - community.general
  roles:
    - libreixp_portal

- hosts: sentry
  tags:
    - sentry
  roles:
    - sentry

- hosts: dns
  become: true
  tags:
    - dns
  roles:
    - netbox_data
    - sfmix_dns
    - bertvv.bind

- hosts: localhost
  tags:
    - route_servers
  roles:
    - netbox_data
    - sfmix_arouteserver_local
    - pierky.arouteserver

- hosts: rs_linux
  tags:
    - route_servers
  roles:
    - sfmix_route_server_linux

# - hosts: rs_openbsd
#   tags:
#     - route_servers
#   roles:
#     - sfmix_route_server_openbsd
