---
- name: Download SSH Keys from GitHub
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Download SSH Keys from GitHub
      ansible.builtin.include_role:
        name: sfmix_server
        tasks_from: download_ssh_keys_from_github.yml

- name: SFMIX Servers
  hosts: servers
  roles:
    - sfmix_server

- name: Setup an ansible control node
  hosts: shell
  tags:
    - shell
  tasks:
    - name: Setup an ansible control node
      ansible.builtin.include_role:
        name: sfmix_server
        tasks_from: ansible_control_node.yml

- name: "Netbox: Prepare server"
  hosts: netbox
  become: true
  tags:
    - netbox
  roles:
    - ixp_netbox

- name: "Netbox: Install Netbox"
  hosts: netbox
  become: true
  tags:
    - netbox
  roles:
    - geerlingguy.postgresql
    - DavidWittman.redis
    - lae.netbox

- name: Metrics Server
  hosts: metrics
  tags:
    - metrics
  roles:
    - docker_engine
    - sflow_rt
    - prometheus
    - grafana

- name: Teleport Auth/Proxy Server
  hosts: teleport
  tags:
    - teleport
  roles:
    - teleport

- name: "Participant Portal: Prepare Server"
  hosts: portal
  become: true
  tags:
    - portal
    - redis
    - postgres
  roles:
    - geerlingguy.postgresql
    - DavidWittman.redis

- name: "Participant Portal: Install LibreIXP"
  hosts: portal
  tags:
    - portal
  roles:
    - libreixp_portal

- name: Install Sentry
  hosts: sentry
  tags:
    - sentry
  roles:
    - sentry

- name: "DNS: SFMIX Zones config"
  hosts: dns
  become: true
  tags:
    - dns
  tasks:
    - name: Load data from netbox
      ansible.builtin.include_role:
        name: netbox_data
    - name: Place sfmix_zones.conf
      ansible.builtin.include_role:
        name: sfmix_dns
        tasks_from: sfmix_zones_config.yml

- name: "DNS: Setup BIND and SFMIX Zone files"
  hosts: dns
  become: true
  tags:
    - dns
  roles:
    - netbox_data
    - bertvv.bind
    - sfmix_dns

- name: "Route Servers/Looking Glass: Generate Configurations"
  hosts: localhost
  tags:
    - route_servers
  roles:
    - netbox_data
    - sfmix_arouteserver
    - pierky.arouteserver

- name: "Route Servers: Publish as-set to ARIN"
  hosts: localhost
  tags:
    - route_servers
    - publish_as_set
  tasks:
    - name: "Publish as-set to ARIN"
      ansible.builtin.include_role:
        name: sfmix_arouteserver
        tasks_from: publish_as_set.yml

- name: "Route Servers: Configure Linux/BIRD"
  hosts: rs_linux
  tags:
    - route_servers
  roles:
    - sfmix_route_server_linux

- name: "Route Servers: Configure OpenBSD/OpenBGPD"
  hosts: rs_openbsd
  tags:
    - route_servers
  roles:
    - sfmix_route_server_openbsd

- name: "Looking Glass: Configure OpenBGPD"
  hosts: looking_glass
  tags:
    - looking_glass
    # FIXME: Migrate usage of participants.json to Alice
    # Currently used by sfmix.org/participants/
    - participants_json
  roles:
    - netbox_data
    - sfmix_looking_glass
    # FIXME: Migrate usage of participants.json to Alice
    # Currently used by sfmix.org/participants/
    - participants_json

- name: "Alice Looking Glass: Install postgresql"
  become: true
  hosts: alice
  tags:
    - alice
  roles:
    - geerlingguy.postgresql

- name: "Alice Looking Glass: Install alice"
  hosts: alice
  tags:
    - alice
  roles:
    - alice

- name: "Alice Looking Glass: participants.json"
  hosts: alice
  tags:
    - participants_json
    - alice
  roles:
    - netbox_data
    - participants_json
