---
- name: Build device configurations
  hosts: peering_switch
  gather_facts: false
  vars:
    config_parts_dir: "{{ (playbook_dir ~ '/sfmix_network_devices.configs/' ~ inventory_hostname) | realpath }}"
  tasks:
    - name: Ensure output configuration directories
      delegate_to: localhost
      ansible.builtin.file:
        dest: "{{ config_parts_dir }}"
        state: directory
        mode: ug=rwx,o=rx
    - name: Build a list of all peering_switch loopbacks
      ansible.builtin.set_fact:
        all_peering_switch_loopbacks: >
          {{ groups['peering_switch'] |
            map('extract', hostvars, 'interfaces') |
            map('selectattr', 'name', 'equalto', 'Loopback0') |
            sum(start=[]) |
            map(attribute='ip_addresses') |
            sum(start=[]) |
            map(attribute='address') |
            ansible.utils.ipaddr('address')
            }}
        local_loopbacks: >
          {{
            interfaces |
            selectattr('name', 'equalto', 'Loopback0') |
            map(attribute='ip_addresses') |
            sum(start=[]) |
            map(attribute='address') |
            ansible.utils.ipaddr('address')
          }}
    - name: Build a list of all other peering_switch loopbacks
      ansible.builtin.set_fact:
        other_peering_switch_loopbacks: >
          {{
            all_peering_switch_loopbacks | difference(local_loopbacks) | sort
          }}
    - name: Build configs
      ansible.builtin.include_role:
        name: sfmix_network_devices
        tasks_from: build_configs.yml
