---
- name: Push switch configs
  hosts: peering_switch
  gather_facts: false
  vars:
    config_parts_dir: "{{ (playbook_dir ~ '/sfmix_network_devices.configs/' ~ inventory_hostname) | realpath }}"
  tasks:
    - name: Load data from netbox
      ansible.builtin.include_role:
        name: netbox_data
    - name: Diff/Push Configs
      ansible.builtin.include_role:
        name: sfmix_network_devices
        tasks_from: push_configs.yml
