---
- name: Build device configurations
  hosts: peering_switch
  gather_facts: false
  vars:
    config_parts_dir: "{{ (playbook_dir ~ '/sfmix_network_devices.configs/' ~ inventory_hostname) | realpath }}"
  tasks:
    - name: Ensure output configuration directories
      delegate_to: localhost
      ansible.builtin.file:
        dest: "{{ config_parts_dir }}"
        state: directory
        mode: ug=rwx,o=rx
    - name: Build configs
      ansible.builtin.include_role:
        name: sfmix_network_devices
        tasks_from: build_configs.yml
