---
- name: Place SFMIX arouteserver templates
  ansible.builtin.copy:
    src: sfmix_templates/
    dest: "{{ arouteserver_templates_dir }}"
    mode: ug=rwx,o=rx

- name: Template a clients.yml file
  ansible.builtin.template:
    src: clients.yml.j2
    dest: "{{ arouteserver_clients_cfg_file }}"
    mode: ug=rw,o=r
