---
- name: Ensure that /opt/sfmix exists
  become: true
  ansible.builtin.file:
    path: /opt/sfmix
    state: directory
    owner: sfmix
    group: sfmix
    mode: ug=rwx,o=r

- name: Place ansible vault secret file
  become: true
  ansible.builtin.copy:
    dest: /opt/sfmix/ansible_vault_secret
    content: "{{ sfmix_ansible_vault_secret }}"
    owner: sfmix
    group: sfmix
    mode: ug=r,o=

- name: Install build-essential
  become: true
  ansible.builtin.apt:
    name: build-essential

- name: Install pipenv
  become: true
  ansible.builtin.pip:
    name: pipenv
