---
- name: Install common packages (Linux)
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - zsh
    - kitty-terminfo

- name: Install qemu-guest-agent on Linux VMs
  when: ansible_system == "Linux" and ansible_virtualization_role == "guest"
  become: true
  ansible.builtin.apt:
    name: qemu-guest-agent

- name: Install qemu-ga on OpenBSD VMs
  when: ansible_system == "OpenBSD" and ansible_virtualization_role == "guest"
  become: true
  community.general.openbsd_pkg:
    name: qemu-ga
    state: present
