---
- name: Set sysctl parameters
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: 'net.ipv6.conf.all.accept_ra', value: '0' }
    - { name: 'net.ipv6.conf.default.accept_ra', value: '0' }
    - { name: 'net.ipv4.conf.all.forwarding', value: '0' }
    - { name: 'net.ipv4.conf.default.forwarding', value: '0' }
    - { name: 'net.ipv6.conf.all.forwarding', value: '0' }
    - { name: 'net.ipv6.conf.default.forwarding', value: '0' }
