---
- name: Stop/disable systemd-resolved
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    enabled: false
    masked: true
    state: stopped

- name: Call stat on /etc/resolv.conf
  become: true
  ansible.builtin.stat:
    path: /etc/resolv.conf
  register: stat_etc_resolv_conf

- name: Remove /etc/resolv.conf symlink to systemd-resolved
  become: true
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent
  when: stat_etc_resolv_conf.stat.islnk

- name: Create /etc/resolv.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/resolv.conf
    content: |
      search sfmix.org
      nameserver {{ sfmix_server_dns_recursor }}
    owner: root
    group: root
    mode: ug=rw,o=r
