---
- name: "SFMIX Admin users: ensure user (Linux)"
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups:
      - sudo
      - sfmix
    append: true
    state: present
  with_items:
    - "{{ sfmix_admin_users }}"
    - "{{ sfmix_host_local_users }}"

- name: "SFMIX Admin users: ensure user (OpenBSD)"
  when: ansible_system == "OpenBSD"
  become: true
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups:
      - wheel
    append: true
    state: present
  with_items:
    - "{{ sfmix_admin_users }}"
    - "{{ sfmix_host_local_users }}"

# This requires that the download_ssh_keys_from_github.yml task has run locally
# already
- name: "SFMIX Admin users: authorized_keys from github"
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', (playbook_dir ~ '/.github_ssh_keys/' ~ item.github_username ~ '.keys')) }}"
  when: item.github_username is defined and not ansible_check_mode
  with_items:
    - "{{ sfmix_admin_users }}"
    - "{{ sfmix_host_local_users }}"

- name: "SFMIX Admin users: authorized_keys from keys_file"
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', item.keys_file) }}"
  when: item.keys_file is defined
  with_items:
    - "{{ sfmix_admin_users }}"
    - "{{ sfmix_host_local_users }}"

- name: "No password for sudo group (Linux)"
  when: ansible_system == "Linux"
  become: true
  community.general.sudoers:
    name: sudoers
    group: sudo
    commands: ALL
    nopassword: true

- name: "No password for wheel group (OpenBSD)"
  when: ansible_system == "OpenBSD"
  become: true
  community.general.sudoers:
    name: sudoers
    group: wheel
    commands: ALL
    nopassword: true
