FROM python:3.9-alpine
RUN apk add g++ git make rrdtool
RUN mkdir -p /opt/RRDReST
RUN git clone https://github.com/tbotnz/RRDReST /opt/RRDReST
# COPY requirements.txt /opt/RRDReST/requirements.txt
WORKDIR /opt/RRDReST
RUN pip3 install -r requirements.txt
# COPY . /opt/RRDReST
ENTRYPOINT ["uvicorn", "rrdrest:rrd_rest"]
CMD ["--host", "0.0.0.0", "--port", "9000"]
