---
- name: "Download SSH Keys from GitHub"
  ansible.builtin.import_tasks: download_ssh_keys_from_github.yml

- name: "SFMIX Server: sshd"
  ansible.builtin.import_tasks: sshd.yml

- name: "SFMIX Server: MOTD"
  ansible.builtin.import_tasks: motd.yml

- name: "SFMIX Server: Docker"
  when: ansible_system == "Linux"
  ansible.builtin.import_tasks:
    file: docker.yml
  tags:
    - docker

- name: "SFMIX Server: sfmix User"
  ansible.builtin.import_tasks: sfmix_user.yml

- name: "SFMIX Server: oxidized User"
  ansible.builtin.import_tasks: oxidized_user.yml

- name: "SFMIX Server: Users"
  ansible.builtin.import_tasks: users.yml

- name: "SFMIX Server: common packages"
  ansible.builtin.import_tasks: common_packages.yml

- name: "SFMIX Server: UFW"
  when: ansible_system == "Linux"
  ansible.builtin.import_tasks:
    file: ufw.yml
  tags: ufw

- name: "SFMIX Server: DNS"
  when: ansible_system == "Linux"
  ansible.builtin.import_tasks:
    file: sfmix_dns.yml
  tags:
    - dns

- name: "SFMIX Server: SNMP Agent"
  ansible.builtin.import_tasks:
    file: snmp_agent.yml
  tags:
    - snmp

- name: "SFMIX Server: Linux sysctl"
  when: ansible_system == "Linux"
  ansible.builtin.import_tasks:
    file: linux_sysctl.yml
  tags:
    - sysctl
