---
- name: Create "sfmix" user (Linux)
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.user:
    name: sfmix
    state: present
    groups:
      - sudo
      - docker
    append: true
    shell: /usr/sbin/nologin

- name: Create "sfmix" user (OpenBSD)
  when: ansible_system == "OpenBSD"
  become: true
  ansible.builtin.user:
    name: sfmix
    state: present
    groups:
      - wheel
    append: true
    shell: /sbin/nologin

- name: Create ~sfmix/.netrc (Linux)
  when: ansible_system == "Linux"
  become: true
  ansible.builtin.template:
    src: netrc.j2
    dest: /home/sfmix/.netrc
    owner: sfmix
    group: sfmix
    mode: o=rw,go=
