---
- name: Configure sshd MaxStartups
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MaxStartups\s+'
    line: "MaxStartups 30:10:80"
    validate: sshd -t -f %s
  notify: Restart sshd

- name: Configure sshd PerSourceMaxStartups
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PerSourceMaxStartups\s+'
    line: "PerSourceMaxStartups 10"
    validate: sshd -t -f %s
  notify: Restart sshd
