---
- name: Re-build alice-lg
  become: true
  community.docker.docker_image:
    build:
      path: /opt/alice/alice-lg
    name: alice-lg
    tag: latest
    source: build
    force_source: true
  notify: Restart alice

- name: Restart alice
  become: true
  community.docker.docker_container:
    name: alice
    restart: true
    state: started
