---
- name: Place httpd.conf
  become: true
  ansible.builtin.template:
    src: httpd.conf.j2
    dest: /etc/httpd.conf
    mode: ug=rw,o=r
  notify: Restart httpd

- name: Place acme-client.conf
  become: true
  ansible.builtin.template:
    src: acme-client.conf.j2
    dest: /etc/acme-client.conf
    mode: ug=rw,o=r

- name: Place bgplg.head
  become: true
  ansible.builtin.template:
    src: bgplg.head.j2
    dest: /var/www/conf/bgplg.head
    mode: ug=rw,o=r

- name: Place SFMIX logo
  become: true
  ansible.builtin.copy:
    src: sfmix.png
    dest: /var/www/htdocs/sfmix.png
    mode: ug=rw,o=r

- name: Enable/start daemons
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - ntpd
    - httpd
    - slowcgi
    - bgplgd

- name: Set bgplgd options
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    regexp: '^bgplgd_flags='
    line: 'bgplgd_flags="-S /var/www/run/bgpd.rsock"'
  notify: Restart bgplgd

- name: Check for /etc/ssl/lg.sfmix.org.fullchain.pem
  become: true
  ansible.builtin.stat:
    path: /etc/ssl/lg.sfmix.org.fullchain.pem
  register: tls_certificate_stat

- name: Run acme-client initially
  become: true
  when: not tls_certificate_stat.stat.exists
  ansible.builtin.command: acme-client lg.sfmix.org
  register: acme_client_command
  changed_when: acme_client_command.rc == 0
  notify: Restart httpd

- name: Run acme-client once a day
  become: true
  ansible.builtin.cron:
    name: run acme-client
    job: acme-client lg.sfmix.org
    minute: "0"
    hour: "2"
    user: root

- name: Enable bgpd
  become: true
  ansible.builtin.service:
    name: bgpd
    enabled: true

- name: Place generated bgpd.conf into /etc/bgpd.candidate.conf
  become: true
  ansible.builtin.template:
    src: bgpd.conf.j2
    dest: /etc/bgpd.candidate.conf
    owner: root
    group: wheel
    mode: ug=rw,o=r

- name: Test candidate bgpd candidate config
  become: true
  ansible.builtin.command:
    cmd: bgpd -n -f /etc/bgpd.candidate.conf
  register: bgpd_config_test
  changed_when: bgpd_config_test.rc == 0

- name: Ensure OpenBGP config backup directory /etc/bgpd_backups
  become: true
  ansible.builtin.file:
    path: /etc/bgpd_backups
    state: directory
    owner: root
    group: wheel
    mode: ug=rwx,o=rx

- name: "Install bgpd Config: Take a backup, place new config, and reload"
  when: bgpd_config_test.rc == 0
  block:
    - name: Check for an existing bgpd config
      become: true
      ansible.builtin.stat:
        path: /etc/bgpd.conf
      register: existing_bgpd_config
    - name: Backup existing bgpd config
      become: true
      when: existing_bgpd_config.stat.exists
      ansible.builtin.copy:
        src: /etc/bgpd.conf
        dest: "/etc/bgpd_backups/{{ '%Y%m%d-%H%M%S' | strftime }}-bgpd.conf"
        remote_src: true
        owner: root
        group: wheel
        mode: ug=rw,o=r
    - name: Install new bgpd config
      become: true
      ansible.builtin.copy:
        src: /etc/bgpd.candidate.conf
        dest: /etc/bgpd.conf
        remote_src: true
        owner: root
        group: wheel
        mode: ug=rw,o=r
      notify: Reload bgpd

- name: Find old bgpd config backups more than 52 weeks old
  become: true
  ansible.builtin.find:
    paths: /etc/bgpd_backups
    age: 52w
  register: old_bgpd_configs

- name: Delete old bgpd config backups
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ old_bgpd_configs.files }}"

# - name: Ensure bgpd is started
#   become: true
#   ansible.builtin.service:
#     name: bgpd
#     state: started

- name: Make cgi-bins executable
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: ugo=rx
  with_items:
    - /var/www/cgi-bin/bgplg
    - /var/www/bin/bgpctl

- name: Make chroot cgi-bins sticky-executable
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    mode: ugo=rx,ugo+s
  with_items:
    - /var/www/bin/ping
    - /var/www/bin/ping6
    - /var/www/bin/traceroute
    - /var/www/bin/traceroute6
