---
- name: Enable bgpd
  become: true
  ansible.builtin.lineinfile:
    path: /etc/rc.conf.local
    regexp: ^bgpd_flags=.*$
    line: 'bgpd_flags=""'
    owner: root
    group: wheel
    mode: ug=rw,o=r
    create: true

- name: Place generated bgpd.conf into /etc/bgpd.candidate.conf
  become: true
  ansible.builtin.template:
    src: bgpd.conf.j2
    dest: /etc/bgpd.candidate.conf
    owner: root
    group: wheel
    mode: ug=rw,o=r

- name: Test the candidate bgpd.conf
  become: true
  ansible.builtin.command:
    cmd: bgpd -n -f /etc/bgpd.candidate.conf
  register: bgpd_config_test
  changed_when: false

- name: Install the candidate bgpd.conf
  become: true
  when: bgpd_config_test.rc == 0
  ansible.builtin.command:
    cmd: mv /etc/bgpd.candidate.conf /etc/bgpd.conf
  changed_when: true
  notify: reload bgpd

- name: Ensure bgpd is started
  ansible.builtin.service:
    name: bgpd
    state: started
