---
- name: "Nodesource: Add apt key"
  become: true
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /etc/apt/keyrings/nodesource.asc
    mode: ug=rw,o=r
    force: true

- name: "Nodesource: add apt repo"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{ alice_nodejs_version }} nodistro main"
    state: present
    filename: nodesource

- name: "Nodesource: nsolid apt preferences"
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/nsolid
    owner: root
    group: root
    mode: ug=rw,o=r
    content: |
      # N|solid Config
      Package: nsolid
      Pin: origin deb.nodesource.com
      Pin-Priority: 600

- name: "Nodesource: nodejs apt preferences"
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/nodejs
    owner: root
    group: root
    mode: ug=rw,o=r
    content: |
      # nodejs Config
      Package: nodejs
      Pin: origin deb.nodesource.com
      Pin-Priority: 600

- name: Install requisite packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - nodejs
    - acl
    - git
    - make

- name: Install golang
  become: true
  community.general.snap:
    name: go
    classic: true

- name: Install yarn
  become: true
  community.general.npm:
    name: yarn
    global: true

- name: Create alice golang directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: sfmix
    group: sfmix
    mode: ug=rwx,o=rx
  with_items:
    - /home/sfmix/go
    - /home/sfmix/go/bin
    - /home/sfmix/go/pkg
    - /home/sfmix/go/src
    - /home/sfmix/go/src/github.com
    - /home/sfmix/go/src/github.com/alice-lg

- name: Clone alice-lg/alice-lg repo
  become: true
  become_user: sfmix
  ansible.builtin.git:
    repo: https://github.com/alice-lg/alice-lg.git
    dest: /home/sfmix/go/src/github.com/alice-lg/alice-lg
    version: "{{ alice_git_repo_version }}"
  notify: Re-build alice

- name: Ensure alice directory
  become: true
  ansible.builtin.file:
    path: /opt/alice
    state: directory
    owner: root
    group: root
    mode: ug=rwx,o=rx

- name: Template alice-lg config
  become: true
  ansible.builtin.template:
    src: alice.conf.j2
    dest: /opt/alice/alice.conf
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Template alice.service systemd unit
  become: true
  ansible.builtin.template:
    src: alice.service.j2
    dest: /etc/systemd/system/alice.service
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Enable/start systemd unit for alice
  notify: Restart alice
  become: true
  ansible.builtin.service:
    name: alice
    enabled: true
    state: started
