---
- name: Set sysctl parameters
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - { name: 'net.ipv4.conf.all.forwarding', value: '1' }
    - { name: 'net.ipv4.conf.default.forwarding', value: '1' }
    - { name: 'net.ipv6.conf.all.forwarding', value: '1' }
    - { name: 'net.ipv6.conf.default.forwarding', value: '1' }
- name: "Tailscale: Install dpkg key from https"
  become: true
  ansible.builtin.apt_key:
    url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    keyring: /usr/share/keyrings/tailscale-archive-keyring.gpg
    state: present
- name: "Tailscale: Add apt list from https list file"
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main"
    state: present
- name: "Tailscale: Install tailscale"
  become: true
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true
