---
- name: "UFW: accept sFlow on OOB"
  become: true
  community.general.ufw:
    rule: allow
    interface_in: oob
    proto: udp
    to_port: 6343

- name: "Sflow-rt: Ensure directories"
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: u=rwx,go=rx
  with_items:
    - "{{ sflow_rt_store_dir }}"

- name: "Sflow-rt: run container: {{ sflow_rt_docker_container }}"
  community.docker.docker_container:
    name: sflow-rt
    image: "{{ sflow_rt_docker_container }}"
    restart_policy: unless-stopped
    network_mode: host
    user: nobody
    command: >-
      -Dixp.bogons=yes
      -Dixp.bgp.router=100.64.0.18
      -Dixp.bgp.as={{ sfmix_sflow_collector_bgp_asn }}
      -Dixp.bgp.id={{ sfmix_sflow_collector_bgp_address }}
      -Dixp.bgp.multipath=yes
      -Dbgp.start=yes
    volumes:
      - "{{ sflow_rt_store_dir }}:/sflow-rt/store"

- name: "Install ~/sfmix/topology.py requirements"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pyeapi
    - python3-requests
    - systemd-cron

- name: "Place ~sfmix/topology.py"
  become: true
  ansible.builtin.template:
    src: topology.py.j2
    dest: /home/sfmix/topology.py
    owner: sfmix
    group: sfmix
    mode: u=rwx,go=

- name: "Run ~sfmix/topology.py every 12 hours"
  become: true
  ansible.builtin.cron:
    name: "SFMIX topology.py"
    user: sfmix
    job: "/home/sfmix/topology.py"
    minute: "0"
    hour: "*/12"

- name: "Import participants.json every 12 hours"
  become: true
  ansible.builtin.cron:
    name: "Import participants.json"
    user: sfmix
    job: 'curl https://lg.sfmix.org/participants.json | curl -d @- -X PUT -H "Content-Type: application/json" http://localhost:8008/app/ixp-metrics/scripts/metrics.js/members/json'
    minute: "30"
    hour: "*/12"
