---
- name: Place mkrdns
  become: true
  ansible.builtin.copy:
    src: mkrdns
    dest: /usr/local/bin/mkrdns
    mode: ug=rwx,o=rx

- name: Run mkrdns
  become: true
  ansible.builtin.command: mkrdns
  register: mkrdns_result
  changed_when: mkrdns_result.rc == 0
  notify: Restart named.service
