---
- name: Create /etc/bind
  become: true
  ansible.builtin.file:
    owner: root
    group: bind
    mode: u=rwx,g=rxs,o=rx
    path: /etc/bind
    state: directory

- name: Place sfmix_zones.conf
  become: true
  notify: Restart named.service
  ansible.builtin.template:
    src: sfmix_zones.conf.j2
    dest: /etc/bind/sfmix_zones.conf
    mode: ug=rw,o=r
