---
- name: Install systemd-cron for certbot
  become: true
  apt:
    pkg: systemd-cron
    state: present

- name: "Firewall: Allow HTTP(S)"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - http
    - https

- name: "Create a dhparams file"
  become: true
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048

- name: "Install HTTPS/Nginx Reverse Proxy"
  become: true
  block:
    - include_role:
        name: "{{ item }}"
      loop:
        - certbot
        - nginx
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_create_if_missing: true
        certbot_certs:
          - domains:
              - sentry.sfmix.org
        nginx_remove_default_vhost: true
        nginx_vhosts:
          - listen: "80"
            server_name: "_"
            return: "301 https://$host$request_uri"
          - listen: "443 ssl http2"
            server_name: sentry.sfmix.org
            extra_parameters: |
              ssl_certificate /etc/letsencrypt/live/sentry.sfmix.org/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/sentry.sfmix.org/privkey.pem;
              ssl_dhparam /etc/ssl/certs/dhparam.pem;
              location = /favicon.ico { access_log off; log_not_found off; }
              location / {
                include proxy_params;
                proxy_pass http://127.0.0.1:9000;
              }
