---
- name: Place bogons.yml
  become: true
  ansible.builtin.copy:
    owner: root
    group: wheel
    mode: u=rw,go=r
    src: bogons.yml
    dest: /opt/arouteserver/bogons.new-ansible.yml

- name: Place general.yml
  become: true
  ansible.builtin.template:
    owner: root
    group: wheel
    mode: u=rw,go=r
    src: general.yml.j2
    dest: /opt/arouteserver/general.new-ansible.yml

- name: Template clients.yml
  become: true
  ansible.builtin.template:
    owner: root
    group: wheel
    mode: u=rw,go=r
    src: clients.yml.j2
    dest: /opt/arouteserver/clients.new-ansible.yml

- name: Build candidate config into /opt/arouteserver/new-openbgpd.new-ansible.conf
  become: true
  ansible.builtin.command: arouteserver openbgpd \
          --target-version 7.8 \
          --cfg /opt/arouteserver/arouteserver.yml \
          --general /opt/arouteserver/general.new-ansible.yml \
          --bogons /opt/arouteserver/bogons.new-ansible.yml \
          --clients /opt/arouteserver/clients.new-ansible.yml \
          --cache-dir /opt/arouteserver/cache \
          --output /opt/arouteserver/new-bgpd.new-ansible.conf
  changed_when: true

- name: Install candidate config
  become: true
  ansible.builtin.command:
    cmd: cp /opt/arouteserver/new-bgpd.new-ansible.conf /etc/bgpd.conf
  changed_when: true

- name: Load candidate config
  become: true
  ansible.builtin.command:
    cmd: bgpctl reload
  changed_when: true
