---
- name: Create /opt/mosquitto/config directory
  become: true
  ansible.builtin.file:
    path: /opt/mosquitto/config
    state: directory
    recurse: true
    mode: ug=rwx,o=rx
    owner: root
    group: root
- name: Create /opt/mosquitto/data directory
  become: true
  ansible.builtin.file:
    path: /opt/mosquitto/data
    state: directory
    recurse: true
    mode: ug=rwx,o=rx
    owner: root
    group: root
- name: Template /opt/mosquitto/config/mosquitto.conf
  become: true
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: /opt/mosquitto/config/mosquitto.conf
    mode: ug=rw,o=r
    owner: root
    group: root
- name: Template /opt/mosquitto/data/password_file
  become: true
  ansible.builtin.template:
    src: password_file.j2
    dest: /opt/mosquitto/data/password_file
    mode: ug=rw,o=r
    owner: root
    group: root
- name: Run docker container eclipse-mosquitto
  become: true
  community.docker.docker_container:
    name: mosquitto
    image: eclipse-mosquitto
    state: started
    restart_policy: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data

# mqtt2prometheus for air sensor
- name: Place mqtt2prometheus config file for air sensors
  become: true
  ansible.builtin.template:
    src: mqtt2prometheus.air_sensor.config.yaml.j2
    dest: /opt/mqtt2prometheus.air_sensor.config.yaml
    mode: ug=rw,o=r
    owner: root
    group: root
  notify: Restart mqtt2prometheus-air-sensor
- name: Run docker container mqtt2prometheus-air-sensor
  become: true
  community.docker.docker_container:
    name: mqtt2prometheus-air-sensor
    network_mode: host
    image: ghcr.io/hikhvar/mqtt2prometheus:latest
    state: started
    restart_policy: always
    volumes:
      - /opt/mqtt2prometheus.air_sensor.config.yaml:/config.yaml
    command: "-config /config.yaml"
