---
- name: Ensure alice directory
  become: true
  ansible.builtin.file:
    path: /opt/alice
    state: directory
    owner: sfmix
    group: sfmix
    mode: ug=rwx,o=rx

- name: Clone alice-lg/alice-lg repo
  become: true
  become_user: sfmix
  ansible.builtin.git:
    repo: "{{ alice_git_repo_url }}"
    version: "{{ alice_git_repo_version }}"
    dest: /opt/alice/alice-lg
  notify: Re-build alice-lg

- name: Trigger alice rebuilt and old container destruction
  ansible.builtin.meta: flush_handlers

- name: "Checkout Alice Theme Repository"
  become: true
  ansible.builtin.git:
    repo: "{{ alice_theme_repo_url }}"
    version: "{{ alice_theme_repo_version }}"
    dest: "{{ alice_theme_directory }}"

- name: "Template {{ alice_config_file }}"
  become: true
  notify: Restart alice
  ansible.builtin.template:
    src: alice.conf.j2
    dest: "{{ alice_config_file }}"
    owner: root
    group: root
    mode: ug=rw,o=r

- name: "Run alice-lg docker container"
  become: true
  community.docker.docker_container:
    name: alice
    image: "alice-lg:{{ alice_git_repo_version | replace('/', '_') }}"
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ alice_config_file }}:{{ alice_config_file }}"
      - "{{ alice_theme_directory }}:{{ alice_theme_directory }}"
    user: nobody
    command: "alice-lg -config {{ alice_config_file }}"

- name: "Create a dhparams file"
  become: true
  community.crypto.openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: 2048

- name: "Firewall: Allow HTTP(S)"
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - http
    - https

- name: "Install HTTPS/Nginx Reverse Proxy"
  become: true
  block:
    - name: "Install certbot for alice domain"
      ansible.builtin.include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: ["nginx.service"]
        certbot_certs:
          - domains:
              - "{{ alice_domain }}"

    - name: "Install certbot for additional vhosts"
      ansible.builtin.include_role:
        name: geerlingguy.certbot
      vars:
        certbot_admin_email: "{{ ixp_primary_tech_contact_email }}"
        certbot_create_if_missing: true
        certbot_create_standalone_stop_services: ["nginx.service"]
        certbot_certs:
          - domains:
              - "{{ item.domain }}"
      loop: "{{ alice_additional_vhosts }}"
      when: alice_additional_vhosts | length > 0

    - name: "Install nginx (base config only)"
      ansible.builtin.include_role:
        name: geerlingguy.nginx
      vars:
        nginx_remove_default_vhost: true
        nginx_server_tokens: "off"
        nginx_extra_http_options: |
          limit_req_zone $binary_remote_addr zone=ip:10m rate=5r/s;
        nginx_vhosts: []

    - name: "Template nginx vhosts config"
      ansible.builtin.template:
        src: nginx-vhosts.conf.j2
        dest: /etc/nginx/conf.d/vhosts.conf
        owner: root
        group: root
        mode: "0644"
      notify: Reload nginx
