---
- name: Locally clone sfmix/sfmix
  delegate_to: localhost
  ansible.builtin.git:
    repo: "git@github.com:sfmix/sfmix.git"
    dest: /tmp/sfmix__sfmix
    depth: 1
    version: main

- name: Install rsync
  become: true
  ansible.builtin.apt:
    pkg: rsync
    state: present

- name: Install pipenv
  become: true
  ansible.builtin.pip:
    name: pipenv

- name: Copy sfmix/sfmix to /opt/sfmix
  become: true
  ansible.posix.synchronize:
    src: /tmp/sfmix__sfmix/
    dest: /opt/sfmix/
    delete: true
    rsync_opts:
      - "--exclude=.git"
  notify: Build virtualenv for ixp_web
  register: copied_sfmix_repo

- name: Set IS_PRODUCTION=True in settings.py
  become: true
  ansible.builtin.lineinfile:
    path: /opt/sfmix/libreixp/ixp_web/ixp_web/settings.py
    regexp: '^IS_PRODUCTION\s*=.*$'
    line: "IS_PRODUCTION = True"

- name: Set DB Host
  become: true
  ansible.builtin.replace:
    path: /opt/sfmix/libreixp/ixp_web/ixp_web/settings.py
    regexp: "{{ item.regex }}"
    replace: "{{ item.replace }}"
  no_log: true
  with_items:
    - { "regex": "CHANGEME_PRODUCTION_DB_PASSWORD", "replace": "{{ postgresql_sfmix_password }}" }
    - { "regex": "CHANGEME_PRODUCTION_DB_PORT", "replace": "5432" }
    - { "regex": "CHANGEME_PRODUCTION_DB_HOST", "replace": "127.0.0.1" }

- name: Template .env file
  notify: Restart libreixp_portal
  become: true
  ansible.builtin.template:
    owner: sfmix
    group: sfmix
    src: dotenv.j2
    dest: /opt/sfmix/libreixp/ixp_web/.env
    mode: ug=rw,o=
  no_log: true

- name: Re-own /opt/sfmix
  become: true
  ansible.builtin.file:
    path: /opt/sfmix
    owner: sfmix
    group: sfmix
    recurse: true
    state: directory

- name: Run DB Migrations
  become: true
  ansible.builtin.command:
    argv:
      - sudo
      - -u
      - sfmix
      - /opt/sfmix/libreixp/ixp_web/.venv/bin/python
      - /opt/sfmix/libreixp/ixp_web/manage.py
      - migrate
  register: django_migration_output
  changed_when: "'No migrations to apply.' not in django_migration_output.stdout"

- name: Build Django static files
  become: true
  ansible.builtin.command:
    argv:
      - sudo
      - -u
      - sfmix
      - /opt/sfmix/libreixp/ixp_web/.venv/bin/python
      - /opt/sfmix/libreixp/ixp_web/manage.py
      - collectstatic
      - --clear
  register: libreixp_portal_django_collectstatic
  changed_when: libreixp_portal_django_collectstatic.rc == 0

- name: Template systemd socket for LibreIXP Portal
  notify: Restart libreixp_portal
  become: true
  ansible.builtin.template:
    src: libreixp_portal.socket.j2
    dest: /etc/systemd/system/libreixp_portal.socket
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Template systemd service for LibreIXP Portal
  notify: Restart libreixp_portal
  become: true
  ansible.builtin.template:
    src: libreixp_portal.service.j2
    dest: /etc/systemd/system/libreixp_portal.service
    owner: root
    group: root
    mode: ug=rw,o=r

- name: Enable systemd units for libreixp_portal
  notify: Restart libreixp_portal
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
  with_items:
    - libreixp_portal.socket
    - libreixp_portal.service
