---
- name: "Install and configure BIRD"
  ansible.builtin.import_tasks: bird.yml

- name: "Install and configure birdwatcher"
  tags:
    - birdwatcher
  ansible.builtin.import_tasks: birdwatcher.yml
