---
- name: "Install and configure BIRD"
  ansible.builtin.import_tasks: bird.yml

- name: "Install and configure birdwatcher"
  tags:
    - birdwatcher
  ansible.builtin.import_tasks: birdwatcher.yml

- name: "Install and configure bird_exporter"
  tags:
    - bird_exporter
  ansible.builtin.import_tasks: bird_exporter.yml

# Install fping, as a place to discover MACs from
- name: "Install fping"
  become: true
  ansible.builtin.apt:
    name: fping
    state: present
